orders/urls.py
from django.urls import path
from .views import CheckoutView

app_name = "orders"

urlpatterns = [
    path("checkout/<uuid:pk>/", CheckoutView.as_view(), name="checkout"),
]

payment_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("subscriptions-house-admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("products.urls")),
    path("", include("orders.urls")),
    path("paypal/", include("paypal.standard.ipn.urls")),
    path("payments/", include("payments.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import HomePageView, ProductListView, ProductDetailView, ClientFormView

app_name = "products"

urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("products/", ProductListView.as_view(), name="product_list"),
    path("client_form/", ClientFormView.as_view(), name="client_form"),
    path("product/<uuid:pk>/", ProductDetailView.as_view(), name="product_detail"),
]

orders/models.py
from django.db import models


class Payment(models.Model):
    transaction_id = models.CharField(max_length=100, unique=True)
    amount = models.DecimalField(decimal_places=2, max_digits=10)
    status = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.transaction_id


class Order(models.Model):
    payment = models.OneToOneField(Payment, on_delete=models.SET_NULL, null=True)
    order_number = models.CharField(max_length=50, unique=True)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone_no = models.CharField(max_length=50)
    email = models.EmailField(max_length=255)
    total = models.DecimalField(decimal_places=2, max_digits=10)
    is_ordered = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.order_number

    @property
    def name(self):
        return f"{self.first_name} {self.last_name}"

products/models.py
from ckeditor.fields import RichTextField
from cloudinary.models import CloudinaryField
from datetime import timedelta
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
import uuid
from django.urls import reverse

User = get_user_model()


class Product(models.Model):
    PLAN_TYPE = (
        ("BASIC", "BASIC"),
        ("POPULAR", "POPULAR"),
        ("ENTERPRISE", "ENTERPRISE"),
    )
    BACKGROUND_TYPE = (
        ("primary", "primary"),
        ("secondry", "secondry"),
        ("danger", "danger"),
    )
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    background_type = models.CharField(choices=BACKGROUND_TYPE, max_length=30)
    plan_type = models.CharField(
        choices=PLAN_TYPE, max_length=30, null=True, blank=True
    )
    price = models.DecimalField(max_digits=8, decimal_places=0)
    title = models.CharField(max_length=50)
    description = RichTextField()
    active = models.BooleanField(default=True)
    is_featured = models.BooleanField(default=False)
    added_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_on", "added_on"]

    def __str__(self):
        if self.plan_type:
            return f"{self.plan_type} - {self.title}"
        else:
            return self.title

    def get_absolute_url(self):
        return reverse("products:product_detail", kwargs={"pk": self.pk})


class OrderItem(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="order_items",
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="order_items"
    )
    paid = models.BooleanField(default=False)
    created_on = models.DateField(default=timezone.now)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.product.title}"

    class Meta:
        ordering = ["-updated_on", "-created_on"]

    @property
    def valid_till(self):
        if self.product.is_featured and self.title.title() != "Get Hired":
            valid_date = self.created_on + timedelta(days=180)
        elif self.product.is_featured and self.title.title() == "Get Hired":
            valid_date = self.created_on + timedelta(days=14)
        else:
            valid_date = self.created_on + timedelta(days=30)
        return valid_date

    @property
    def customer_name(self):
        return self.user.name

    @property
    def customer_email(self):
        return self.user.email

    @property
    def customer_phoneNo(self):
        return self.user.phone_no


JOB_CHOICES = (
    ("REMOTE", "REMOTE"),
    ("HYBRID", "HYBRID"),
    ("ON-SITE", "ON-SITE"),
)
YES_OR_NO = (
    (True, "Yes"),
    (False, "No"),
)


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name="client_forms",
    )
    address = models.CharField(max_length=255)
    job_titles = models.CharField(max_length=255)
    ethnicity = models.CharField(max_length=50)
    race = models.CharField(max_length=50)
    location = models.CharField(max_length=255)
    salary = models.CharField(max_length=255)
    native_language = models.CharField(max_length=100)
    nationality = models.CharField(max_length=100)
    authorized = models.BooleanField(choices=YES_OR_NO)
    sponsorship = models.BooleanField(choices=YES_OR_NO)
    job_type = models.CharField(choices=JOB_CHOICES, max_length=20)
    disability = models.CharField(max_length=255, null=True, blank=True)
    resume = CloudinaryField("image")
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-updated_on", "-created_on"]
        verbose_name_plural = "Client Forms"

    def __str__(self):
        return f"{self.user.name}'s LinkedIn Form"

products/forms.py
from django import forms
from .models import Client, JOB_CHOICES, YES_OR_NO
from .validators import allow_only_images


class ContactForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=True,
        widget=forms.TextInput(attrs={"placeholder": "Name", "class": "form-control"}),
    )
    email = forms.CharField(
        max_length=255,
        required=True,
        widget=forms.EmailInput(
            attrs={"placeholder": "Email", "class": "form-control"}
        ),
    )
    phone_no = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Phone No", "class": "form-control"}
        ),
    )
    subject = forms.CharField(
        max_length=255,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Subject", "class": "form-control"}
        ),
    )
    comment = forms.CharField(
        required=False,
        widget=forms.Textarea(
            attrs={"placeholder": "Comment", "class": "form-control"}
        ),
    )


class ClientForm(forms.ModelForm):
    name = forms.CharField(
        max_length=255,
        required=True,
        widget=forms.TextInput(
            attrs={"placeholder": "Enter your name...", "class": "form-control mb-4"}
        ),
    )
    email = forms.CharField(
        max_length=255,
        required=True,
        widget=forms.EmailInput(
            attrs={"placeholder": "Enter your email...", "class": "form-control mb-4"}
        ),
    )
    phone_no = forms.CharField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Enter your phone no...",
                "class": "form-control mb-4",
            }
        ),
    )

    job_type = forms.CharField(max_length=20, widget=forms.Select(choices=JOB_CHOICES))
    authorized = forms.ChoiceField(choices=YES_OR_NO)
    sponsorship = forms.ChoiceField(choices=YES_OR_NO)
    resume = forms.FileField(
        widget=forms.FileInput(attrs={"class": "form-control mb-4"}),
        validators=[allow_only_images],
    )

    class Meta:
        model = Client
        fields = [
            "name",
            "email",
            "phone_no",
            "address",
            "job_titles",
            "ethnicity",
            "race",
            "location",
            "salary",
            "native_language",
            "nationality",
            "disability",
            "job_type",
            "authorized",
            "sponsorship",
            "disability",
            "resume",
        ]

    def __init__(self, *args, **kwargs):
        super(ClientForm, self).__init__(*args, **kwargs)
        self.fields["address"].widget.attrs.update(
            {"placeholder": "Enter your address...", "class": "form-control mb-4"}
        )
        self.fields["job_titles"].widget.attrs.update(
            {
                "placeholder": "Enter at least 3 job titles...",
                "class": "form-control mb-4",
            }
        )
        self.fields["ethnicity"].widget.attrs.update(
            {"placeholder": "Enter your ethnicity...", "class": "form-control mb-4"}
        )
        self.fields["race"].widget.attrs.update(
            {"placeholder": "Enter your race...", "class": "form-control mb-4"}
        )
        self.fields["location"].widget.attrs.update(
            {
                "placeholder": "Enter your preferred location...",
                "class": "form-control mb-4",
            }
        )
        self.fields["salary"].widget.attrs.update(
            {
                "placeholder": "Enter your salary requirements...",
                "class": "form-control mb-4",
            }
        )
        self.fields["native_language"].widget.attrs.update(
            {
                "placeholder": "Enter your native language...",
                "class": "form-control mb-4",
            }
        )
        self.fields["nationality"].widget.attrs.update(
            {"placeholder": "Enter your nationality...", "class": "form-control mb-4"}
        )
        self.fields["disability"].widget.attrs.update(
            {"placeholder": "Optional...", "class": "form-control mb-4"}
        )
        self.fields["job_type"].widget.attrs.update({"class": "form-control mb-4"})
        self.fields["authorized"].widget.attrs.update({"class": "form-control mb-4"})
        self.fields["sponsorship"].widget.attrs.update({"class": "form-control mb-4"})

products/views.py
import time
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views.generic import View, ListView, DetailView
from django.conf import settings
from paypal.standard.forms import PayPalPaymentsForm
from .models import Product, OrderItem, Client
from .forms import ContactForm, ClientForm
from .utils import special_product


class HomePageView(View):
    def get(self, request, *args, **kwargs):
        product_list = Product.objects.filter(active=True)[:6]
        context = {"product_list": product_list, "form": ContactForm}
        return render(request, "products/index.html", context)

    def post(self, request, *args, **kwargs):
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data["subject"]
            name = form.cleaned_data["name"]
            email_from = form.cleaned_data["email"]
            phone_no = form.cleaned_data["phone_no"]
            message = f'{form.cleaned_data["comment"]}.\n\nSent by {name}.\nPhone No is {phone_no}.\nEmail is {email_from}'
            receipient_list = [
                settings.EMAIL_HOST_USER,
            ]
            send_mail(
                subject,
                message,
                email_from,
                receipient_list,
                fail_silently=False,
            )
            messages.success(request, "Your message was sent successfully")
            return redirect("products:index")


class ProductListView(ListView):
    model = Product
    template_name = "products/product_list.html"
    context_object_name = "product_list"
    paginate_by = 6

    def get_queryset(self):
        product_list = Product.objects.filter(active=True)
        return product_list


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = "products/product_detail.html"
    context_object_name = "product"
    login_url = "account_signup"

    def get_object(self):
        product = get_object_or_404(Product, id=self.kwargs.get("pk"))
        return product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product = self.get_object()
        user = self.request.user
        order_item, created = OrderItem.objects.get_or_create(
            product=product, user=user, paid=False
        )
        host = self.request.get_host()
        return_url = (
            f"http://{host}{reverse('products:client_form')}"
            if product.title.title() == "Get Hired"
            and product.is_featured
            and not Client.objects.filter(user=user).exists()
            else f"http://{host}{reverse('payments:payment_completed')}"
        )
        paypal_dict = {
            # "business": settings.PAYPAL_RECEIVER_EMAIL,
            "business": "sb-47n431224883123@business.example.com",
            "amount": order_item.product.price,
            "item_name": order_item.product.title,
            "invoice": str(order_item.id),
            "currency_code": "USD",
            "notify_url": f"http://{host}{reverse('paypal-ipn')}",
            "return": return_url,
            "cancel_return": f"http://{host}{reverse('payments:payment_cancelled')}",
        }
        form = PayPalPaymentsForm(initial=paypal_dict)
        context["paypal_dict"] = paypal_dict
        context["form"] = form
        if not settings.PAYPAL_TEST:
            context["action"] = "https://www.paypal.com/cgi-bin/webscr"
        else:
            context["action"] = "https://www.sandbox.paypal.com/cgi-bin/webscr"
        return context


class ClientFormView(LoginRequiredMixin, View):
    login_url = "account_signup"

    def get(self, request, *args, **kwargs):
        product = Product.objects.get(title="Get Hired", is_featured=True)
        order_item = OrderItem.objects.filter(
            product=product, user=request.user, paid=True
        )
        if order_item.exists():
            form = ClientForm(
                initial={
                    "name": request.user.name,
                    "email": request.user.email,
                    "phone_no": request.user.phone_no,
                }
            )
            context = {"form": form}
            return render(request, "products/client_form.html", context)
        else:
            context = {"product": product}
            return render(request, "403.html", context)

    def post(self, request, *args, **kwargs):
        form = ClientForm(request.POST, request.FILES)
        print(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get("name")
            email = form.cleaned_data.get("email")
            phone_no = form.cleaned_data.get("phone_no")
            product = special_product()
            client_form = form.save(commit=False)
            request.user.name = name
            request.user.email = email
            request.user.phone_no = phone_no
            request.user.save()
            client_form.user = request.user
            client_form.product = product
            client_form.save()
            messages.success(request, "Your form was submitted successfully!")
            return redirect("products:product_list")
        else:
            context = {"form": form}
            return render(request, "products/client_form.html", context)

templates/products/product_detail.html
{% extends '_base.html' %}
{% load static %}

{% block title %}| {{ product.title }}{% endblock title %}

{% block content %}
  <div class="background-container">
    <div class="container">
      <div class="row h-100 justify-content-center align-items-center">
        <div class="col-10 col-md-8 col-lg-6 form-margin">
              <div
                class="pricing_item_detail text-center top40 wow fadeIn"
                data-wow-deeay="400ms"
                {% if product.plan_type %}style="height: 550px;"{% endif %}
                >
                  {% if product.plan_type %}
                    <h3 class="font-light darkcolor"><b>{{ product.plan_type|upper }}</b></h3>
                    <p class="bottom30">{{ product.title|title }}</p>
                  {% else %}
                    <h3 class="font-light darkcolor"><b>{{ product.title }}</b></h3>
                  {% endif %}
                    <div class="pricing_price darkcolor">
                        <span class="pricing_currency">
                            <b>${{ product.price }}</b></span>/
                            {% if product.is_featured and product.title|title == "Get Hired" %}
                            14days
                            {% elif product.is_featured %}
                            6months
                            {% else %}
                            month
                            {% endif %}
                    </div>
                    <p>{{ product.description|safe|linebreaks }}</p>
                    {% comment %} <form action="{{ action }}" method="post">
                      <input type="hidden" name="cmd" value="_xclick" id="id_cmd">
                      <input type="hidden" name="charset" value="utf-8" id="id_charset">
                      <input type="hidden" name="currency_code" value="USD" id="id_currency_code">
                      <input type="hidden" name="no_shipping" value="1" id="id_no_shipping">
                      <input type="hidden" name="business" value="{{ paypal_dict.business }}" id="id_business">
                      <input type="hidden" name="amount" value="{{ paypal_dict.amount }}" id="id_amount">
                      <input type="hidden" name="item_name" value="{{ paypal_dict.item_name }}" id="id_item_name">
                      <input type="hidden" name="invoice" value="{{ paypal_dict.invoice }}" id="id_invoice">
                      <input type="hidden" name="notify_url" value="{{ paypal_dict.notify_url }}" id="id_notify_url">
                      <input type="hidden" name="cancel_return" value="{{ paypal_dict.cancel_return }}" id="id_cancel_return">
                      <input type="hidden" name="return" value="{{ paypal_dict.return }}" id="id_return">
                      <div class="paypal">
                        <input type="image" src="{% static 'images/paypal-logo.png' %}" name="submit" class="paypal-logo">
                      </div>
                    </form> {% endcomment %}
                    {% comment %} <div id="paypal-button-container"></div> {% endcomment %}
                    {% comment %} <div id="smart-button-container">
                      <div style="text-align: center;">
                        <div id="paypal-button-container"></div>
                      </div>
                    </div> {% endcomment %}
                    <div id="paypal-button-container"></div>
            </div>
          </div>
        </div>
    </div>
  </div>

  <script>
    const price = "{{ product.price }}";
    function initPayPalButton() {
      paypal.Buttons({
        style: {
          shape: 'rect',
          color: 'blue',
          layout: 'vertical',
          label: 'paypal',
          
        },
    
        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{"amount":{"currency_code":"USD","value":price}}]
          });
        },
    
        onApprove: function(data, actions) {
          return actions.order.capture().then(function(orderData) {
            
            // Full available details
            console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
    
            // Show a success message within this page, e.g.
            const element = document.getElementById('paypal-button-container');
            element.innerHTML = '';
            element.innerHTML = '<h3>Thank you for your payment!</h3>';
    
            // Or go to another URL:  actions.redirect('thank_you.html');
            
          });
        },
    
        onError: function(err) {
          console.log(err);
        }
      }).render('#paypal-button-container');
    }
    initPayPalButton();
  </script>

{% endblock content %}

templates/products/product_list.html
{% extends '_base.html' %}
{% load static %}

{% block title %}| Products{% endblock title %}


{% block content %}

<!--Pricings-->
    <div class="background-container">
        <section class="padding" id="pricing">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center" style="margin-top: 120px;">
                    <h2 style="color: #cbcbcb;">
                    <span>Pricing</span> Tables <span class="divider-center"></span>
                    </h2>
                    <p class="bottom30 margin10" style="color: #cbcbcb;">
                    Get the features you need and save money with our flexible pricing
                    plans.
                    </p>
                    </div>
                </div>
                <div class="row">
                    {% for product in product_list %}
                        <div class="col-md-4">
                            <div
                            class="pricing_item {{ product.background_type }} text-center top40 wow fadeIn"
                            data-wow-deeay="400ms"
                            >
                                {% if product.title|title == "Get Hired" and product.plan_type is None %}
                                    <h3 class="font-light darkcolor"><b>{{ product.title }}</b></h3>
                                {% elif product.title|title == "Get Hired" %}
                                    <h3 class="font-light darkcolor"><b>{{ product.plan_type|title }}</b></h3>
                                    <p class="bottom10">{{ product.title }}</p>
                                {% else %}
                                    <h3 class="font-light darkcolor"><b>{{ product.title}}</b></h3>
                                {% endif %}
                                    <div class="pricing_price darkcolor">
                                    <span class="pricing_currency">
                                        <b>${{ product.price }}</b></span>/
                                        {% if product.is_featured and product.title|title == "Get Hired" %}
                                        14days
                                        {% elif product.is_featured %}
                                        6months
                                        {% else %}
                                        month
                                        {% endif %}
                                </div>
                                <p>{{ product.description|safe|linebreaks }}</p>
                                <a class="btn_common btn_{{ product.background_type }}" 
                                   href="{% url 'orders:checkout' product.id %}"
                                    >Choose Plan</a
                                >
                            </div>
                        </div>
                    {% endfor %}
                    <div id="wrapper">
                        <div class="b-pagination-outer">
                            <ul id="border-pagination">
                            {% if page_obj.has_previous %}
                                <li><a href="?page={{ page_obj.previous_page_number }}">«</a></li>
                            {% else %}
                                <li><a href="#" tabindex="-1" aria-disabled="True" class="disabled">«</a></li>
                            {% endif %}

                            {% for i in page_obj.paginator.page_range %}
                                {% if page_obj.number == i %}
                                    <li><a href="?page={{ i }}" class="active">{{ i }}</a></li>
                                {% else %}
                                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                                <li><a href="?page={{ page_obj.next_page_number }}">»</a></li>
                            {% else %}
                                <li ><a href="#" tabindex="-1" aria-disabled="True" class="disabled">»</a></li>
                            {% endif %}
                            </ul> 
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--Pricings-->
    </div>
{% endblock content %}