orders/urls.py
from django.urls import path
from .views import CheckoutView

app_name = "orders"

urlpatterns = [
    path("checkout/<uuid:pk>/", CheckoutView.as_view(), name="checkout"),
]

payment_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("subscriptions-house-admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("products.urls")),
    path("", include("orders.urls")),
    path("paypal/", include("paypal.standard.ipn.urls")),
    path("payments/", include("payments.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import HomePageView, ProductListView, ProductDetailView, ClientFormView

app_name = "products"

urlpatterns = [
    path("", HomePageView.as_view(), name="index"),
    path("products/", ProductListView.as_view(), name="product_list"),
    path("client_form/", ClientFormView.as_view(), name="client_form"),
    path("product/<uuid:pk>/", ProductDetailView.as_view(), name="product_detail"),
]

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <title>Subscriptions House {% block title %}{% endblock title %}</title>
   <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/cubeportfolio.min.css' %}">
   <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'css/settings.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
       
   <link rel="icon" href="{% static 'images/favicon.png' %}">
   <!-- PayPal JS SDK -->
   <script src="https://www.paypal.com/sdk/js?client-id={{ PAYPAL_CLIENT_ID }}&currency=USD"></script>

</head>

<body data-spy="scroll" data-target=".navbar-nav" data-offset="90">
    {% include '_navbar.html' %}
    {% if messages %}
        {% for message in messages %} 
            <div
                {% if message.tags and message.tags == "error" %} 
                class="alert alert-danger alert-dismissible"
                {% elif message.tags %} 
                class="alert alert-{{ message.tags }} alert-dismissible"
                {% endif %}
                role="alert" id="box">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}{% endblock content %}
    {% include '_footer.html' %}
    {% include '_scripts.html' %}
</body>

templates/_footer.html
{% load static %}

<!--FOOTER-->
<footer id="contactus" class="footer-padding">
    <div class="container">
        <div class="row">
            <div
            class="col-md-4 col-sm-12 footer_panel heading_space wow fadeIn"
            data-wow-delay="300ms"
            >
            <h3 class="heading bottom30">
            About Us<span class="divider-left"></span>
            </h3>
            <a href="{% url 'products:index' %}" class="footer_logo bottom25"
            ><img src="{% static 'images/logo-white.png' %}" alt="Webox"
            /></a>
            <p>
            Welcome to Subscription House, We are dedicated to helping job seekers
            land a job quickly and build their career.
            </p>
            <ul class="social_icon top25">
            <li>
                <a href="https://www.facebook.com/subscriptionshouse" target="_blank"><i class="fa fa-facebook"></i></a>
            </li>
            <li>
                <a href="https://www.linkedin.com/company/subscriptions-house/" target="_blank"><i class="fa fa-linkedin"></i></a>
            </li>
            </ul>
            </div>
            <div
            class="col-md-4 col-sm-12 footer_panel heading_space wow fadeIn"
            data-wow-delay="350ms"
            >
            <h3 class="heading bottom30">
            Quick Links<span class="divider-left"></span>
            </h3>
            <div class="row">
            <div class="col-md-12 col-xs-12">
                <ul class="links">
                <li><a href="{% url 'products:index' %}#home">Home</a></li>
                <li><a href="{% url 'products:index' %}#aboutus">Services</a></li>
                <li><a href="{% url 'products:index' %}#gallery">About</a></li>
                <li><a href="{% url 'products:index' %}#pricing">Packages</a></li>
                <li><a href="{% url 'products:index' %}#faq">FAQs</a></li>
                <li><a href="{% url 'products:index' %}#reviews">Testimonials</a></li>
                <li><a href="{% url 'products:index' %}#contactus">Contact Us</a></li>
                </ul>
            </div>
            </div>
            </div>
            <div
            class="col-md-4 col-sm-12 footer_panel heading_space wow fadeIn"
            data-wow-delay="400ms"
            >
            <h3 class="heading bottom30">
            Keep in Touch <span class="divider-left"></span>
            </h3>
            {% comment %} <p class=" address"><i class="fa fa-map-marker"></i>Lahore, Punjab, Pakistan.</p> {% endcomment %}
            <p class="address">
            <i class="fa fa-envelope-o"></i
            ><a href="mailto:subscriptionhouse.1@gmail.com">subscriptionhouse.1@gmail.com</a>
            </p>
            </div>
        </div>
    </div>
</footer>
<div class="copyright">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center wow fadeInUp" data-wow-delay="300ms">
            <p>
            Copyright &copy; 2021 - 2023
            <a href="javascript:void(0)">subscription House</a>. all rights
            reserved.
            </p>
            </div>
        </div>
    </div>
</div>
<!--FOOTER ends-->

templates/_navbar.html
{% load static %} {% comment %}
<!--Loader-->
<div class="loader">
  <div class="spinner centered">
    <div class="spinner-container container1">
      <div class="circle1"></div>
      <div class="circle2"></div>
      <div class="circle3"></div>
      <div class="circle4"></div>
    </div>
    <div class="spinner-container container2">
      <div class="circle1"></div>
      <div class="circle2"></div>
      <div class="circle3"></div>
      <div class="circle4"></div>
    </div>
  </div>
</div>
<!--Loader ends-->
{% endcomment %}

<!-- header -->
<header class="site-header">
  <nav class="navbar navbar-expand-lg transparent-bg hvr-multi">
    <div class="container">
      <a class="navbar-brand" href="/">
        <img
          src="{% static 'images/logo-white.png' %}"
          alt="logo"
          class="logo-default"
        />
        <img
          src="{% static 'images/logo.png' %}"
          alt="logo"
          class="logo-scrolled"
        />
      </a>
      <button
        class="navbar-toggler navbar-toggler-right collapsed"
        type="button"
        data-toggle="collapse"
        data-target="#wenav"
      >
        <span> </span>
        <span> </span>
        <span> </span>
      </button>
      <div class="collapse navbar-collapse" id="wenav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'products:index' %}#home">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'products:product_list' %}"
              >Packages</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'products:index' %}#reviews"
              >Testimonials</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'products:index' %}#aboutus"
              >Services</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'products:index' %}#gallery"
              >About</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'products:index' %}#faq">FAQs</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'products:index' %}#contactus"
              >contact</a
            >
          </li>
          {% comment %} {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a
              class="nav-link"
              href="{% url 'account_login' %}?next={{request.path}}"
              >Log In</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account_signup' %}?next={{request.path}}">Register</a>
          </li>
          {% endif %} {% endcomment %}
        </ul>
      </div>

      <div class="nav-social">
        <ul class="social_icon noborder">
          <li>
            <a
              class="facebook"
              href="https://www.facebook.com/subscriptionshouse"
              target="_blank"
              ><i class="fa fa-facebook"></i>
            </a>
          </li>
          <li>
            <a
              href="https://www.linkedin.com/company/subscriptions-house/"
              target="_blank"
              ><i class="fa fa-linkedin"></i>
            </a>
          </li>
        </ul>
      </div>

      {% comment %}
      <!--side menu open button-->
      <a
        href="javascript:void(0)"
        class="d-none d-lg-inline-block sidemenu_btn"
        id="sidemenu_toggle"
      >
        <span></span> <span></span> <span></span>
      </a>
      {% endcomment %}
    </div>
  </nav>

  <!-- side menu -->
  {% comment %}
  <div class="side-menu">
    <div class="inner-wrapper">
      <span class="btn-close" id="btn_sideNavClose"><i></i><i></i></span>
      <a class="navbar-brand" href="/">
        <img src="{% static 'images/logo.png' %}" alt="logo" />
      </a>
      <nav class="side-nav w-100">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link pagescroll" href="#home">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link pagescroll" href="{% url 'products:index' %}"
              >Services</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link pagescroll" href="{% url 'products:index' %}"
              >About</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link pagescroll" href="{% url 'products:index' %}"
              >Testimonials</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link pagescroll" href="{% url 'products:index' %}"
              >Packages</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link pagescroll" href="{% url 'products:index' %}"
              >FAQs</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link pagescroll" href="{% url 'products:index' %}"
              >Contact</a
            >
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link pagescroll" href="{% url 'account_logout' %}"
              >Log Out</a
            >
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link pagescroll" href="{% url 'account_login' %}"
              >Log In</a
            >
          </li>
          <li class="nav-item">
            <a class="nav-link pagescroll" href="{% url 'account_signup' %}"
              >Register</a
            >
          </li>
          {% endif %}
        </ul>
      </nav>
      <div class="side-footer w-100">
        <ul class="social-icons-simple white top40">
          <li>
            <a href="javascript:void(0)"><i class="fa fa-facebook"></i> </a>
          </li>
          <li>
            <a href="javascript:void(0)"><i class="fa fa-instagram"></i> </a>
          </li>
          <li>
            <a href="javascript:void(0)"><i class="fa fa-twitter"></i> </a>
          </li>
        </ul>
        <p class="darkcolor">&copy; 2023 Subscriptions House.</p>
      </div>
    </div>
  </div>
  {% endcomment %}
  <a id="close_side_menu" href="javascript:void(0);"></a>
</header>
<!-- header -->

templates/_scripts.html
{% load static %}

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

<!--Bootstrap Core-->
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!--to view items on reach-->
<script src="{% static 'js/jquery.appear.js' %}"></script>

<!--Equal-Heights-->
<script src="{% static 'js/jquery.matchHeight-min.js' %}"></script>

<!--Owl Slider-->
<script src="{% static 'js/owl.carousel.min.js' %}"></script>

<!--number counters-->
<script src="{% static 'js/jquery-countTo.js' %}"></script>

<!--Parallax Background-->
<script src="{% static 'js/parallaxie.js' %}"></script>

<!--Cubefolio Gallery-->
<script src="{% static 'js/jquery.cubeportfolio.min.js' %}"></script>

<!--FancyBox popup-->
<script src="{% static 'js/jquery.fancybox.min.js' %}"></script>

<!--Morphing Text-->
<script src="{% static 'js/morphext.min.js' %}"></script>

<!--Particles-->
<script src="{% static 'js/particles.min.js' %}"></script>

<!--WOw animations-->
<script src="{% static 'js/wow.min.js' %}"></script>

<!--Revolution SLider-->
<script src="{% static 'js/revolution/jquery.themepunch.tools.min.js' %}"></script>
<script src="{% static 'js/revolution/jquery.themepunch.revolution.min.js' %}"></script>
<!-- SLIDER REVOLUTION 5.0 EXTENSIONS  (Load Extensions only on Local File Systems !  The following part can be removed on Server for On Demand Loading) -->
<script src="{% static 'js/revolution/extensions/revolution.extension.actions.min.js' %}"></script>
<script src="{% static 'js/revolution/extensions/revolution.extension.carousel.min.js' %}"></script>
<script src="{% static 'js/revolution/extensions/revolution.extension.kenburn.min.js' %}"></script>
<script src="{% static 'js/revolution/extensions/revolution.extension.layeranimation.min.js' %}"></script>
<script src="{% static 'js/revolution/extensions/revolution.extension.migration.min.js' %}"></script>
<script src="{% static 'js/revolution/extensions/revolution.extension.navigation.min.js' %}"></script>
<script src="{% static 'js/revolution/extensions/revolution.extension.parallax.min.js' %}"></script>
<script src="{% static 'js/revolution/extensions/revolution.extension.slideanims.min.js' %}"></script>
<script src="{% static 'js/revolution/extensions/revolution.extension.video.min.js' %}"></script>

<!--Google Map-->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAJ97zN_MClQ8BnmJJOCY165S2QEYvbIis"></script>
<script src="{% static 'js/map.js' %}"></script>
<script src="{% static 'js/functions.js' %}"></script> 


<script>
    setTimeout(() => {
        const box = document.getElementById('box');
        box.style.display = 'none';
    }, 5000); 
</script>